version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_backlog
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: backlog_db
      MYSQL_USER: backlog_user
      MYSQL_PASSWORD: backlog_pass
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

  api:
    build: ./api
    container_name: node_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql          # <-- Nom du service MySQL
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"              # phpMyAdmin accessible sur http://localhost:8080
    depends_on:
      - mysql

volumes:
  mysql_data:
